name: Build succeeds on PR

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Build the project
    runs on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Generate prisma client
        run: npm run db:prisma

      - name: Run Build
        run: npm run build

  #     - run: npm install --no-optional && npm audit fix --